import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    myanmarSub : {
        nav_sub_1 : "ဆောင်ရွက်နိုင်သည့် အရာများ",
        nav_sub_2 : "သွားလာလည်ပတ်ရန် နေရာများ",
        nav_sub_3 : "သင်၏ ခရီးစဉ်",
        nav_sub_4 : "ဆက်တင်များ",
        navDrop_title_sub_1 : "တည်နေရာ ဦးတည်ချက်များ",
        navDrop_title_sub_2 : "တည်းခိုရန် နေရာများ",
        navDrop_title_sub_3 : "အမျိုအစားများ",
        navDrop_title_sub_4 : "လည်ပတ်ရန် အကြံပြုချက်များ",
        navDrop_title_sub_5 : "ရာသီလိုက် ပွဲတော်များ",
        navDrop_sub_1 : "ရန်ကုန်",
        navDrop_sub_2 : "မန္တလေး",
        navDrop_sub_3 : "ပုဂံ",
        navDrop_sub_4 : "ပြင်ဦးလွင်",
        navDrop_sub_5 : "တောင်ကြီး",
        navDrop_sub_6 : "ကလော",
        navDrop_sub_7 : "မော်လမြိုင်",
        navDrop_sub_8 : "အင်းတော်ကြီး",
        navDrop_sub_9 : "အင်းလေး",
        navDrop_sub_10 : "ပူတာအို",
        navDrop_sub_11 : "ရခိုင်",
        navDrop_sub_12 : "အားလုံး",
        navDrop_sub_13 : "ဟိုတယ်များ",
        navDrop_sub_14 : "ဘန်ကလို",
        navDrop_sub_15 : "ဇိမ်ခံအိမ်တော်ကြီးများ",
        navDrop_sub_16 : "အပန်းဖြေစခန်းများ",
        navDrop_sub_17 : "စားသောက်ဆိုင်များ",
        navDrop_sub_18 : "ကမ်းခြေ",
        navDrop_sub_19 : "မြိုပြနေရာ",
        navDrop_sub_20 : "ရေပူစမ်း",
        navDrop_sub_21 : "သဘာဝ အလှတရား နှင့် တောရိုင်းတိရစ္ဆာန်",
        navDrop_sub_22 : "ဂေါက်ရိုက်ခြင်း",
        navDrop_sub_23 : "သမိုင်းဝင် အမွေအနှစ်",
        navDrop_sub_24 : "အကောင်းဆုံး အချိန်တွေကို ကျွန်တော်တို့နှင့် ကုန်ဆုံးလိုက်ပါ",
        navDrop_sub_25 : "ခရီးတစ်ခုအတွက် ဘောနပ်ကူပွန် ၁၀၀၀ပွိုင့် ရယူပါ",
        navDrop_sub_26 : "ရိုးရာပွဲလမ်းသဘင်များအတွက် လျော့ဈေး",
        navDrop_sub_27 : "ပထမဆုံအကြိမ် ဝယ်ယူခြင်းအတွက် လျော့ဈေး",
        navDrop_sub_28 : "ယခု စာရင်းပေးသွင်းရန်",
        navDrop_sub_29 : "ရွှေတိဂုံ စေတီဘုရား",
        navDrop_sub_30 : "မန္တလေး နန်းတော်",
        navDrop_sub_31 : "ချောင်းသာ ကမ်းခြေ",
        navDrop_sub_32 : "ငွေဆောင် ကမ်းခြေ",
        navDrop_sub_33 : "ပုဂံ (ညောင်ဦး)",
        navDrop_sub_34 : "အင်းဝ (မန္တလေး)",
        navDrop_sub_35 : "ဦးပိန် တံတား",
        navDrop_sub_36 : "ကျိုက်ထီးရိုး ဘုရား",
        navDrop_sub_37 : "အင်းတော်ကြီးကန်",
        navDrop_sub_38 : "အင်းလေးကန်",
        navDrop_sub_39 : "ရန်ကုန် တိရစ္ဆာန် ဥယျာဉ် ",
        navDrop_sub_40 : "ပူတာအို တောင်တက်ခရီးစဉ်",
        navDrop_sub_41 : "မဟာ သင်္ကြန် ပွဲတော်",
        navDrop_sub_42 : "သီတင်းကျွတ် ပွဲတော်",
        navDrop_sub_43 : "တောင်ကြီး တန်ဆောင်တိုင်",
        navDrop_sub_44 : "ကချင် မနှော ပွဲတော်",
        navDrop_sub_45 : "ရှမ်းနှစ်သစ်ကူး ပွဲတော်",
        navDrop_sub_46 : "အင်းလေး-ဖောင်တော်ဦး ဘုရား ပွဲတော်",
        heroLand_sub_1 : "မြန်မာနိုင်ငံရှိ အပန်းဖြေစခန်းများမှ",
        heroLand_sub_2 : "သင့်အား ကြိုဆိုနေပါသည်",
        heroLand_sub_3 : "ဇိမ်ခံအပန်းဖြေနေရာ အသစ်များကို ရှာဖွေလိုက်ပါ",
        heroLand_sub_4 : "ပိုမိုလေ့လာရန်",
        home_sub_1 : "သင်၏အချိန်တွေကို မြန်မာနိုင်ငံတွင် ကုန်ဆုံးလိုက်ပါ",
        home_sub_2 :"           မြန်မာနိုင်ငံသည် လူသိနည်းသော သဘာဝတရားများ၊ ယဉ်ကျေးမှုအမွေအနှစ်များနှင့်  အံ့သြဖွယ်အကောင်းဆုံး အာရှခရီးသွားအတွေ့အကြုံများထဲမှ တစ်ခုဖြစ်ပါသည်။ မြန်မာနိုင်ငံသည် ဆီးနှင်းထူထပ်သော ဟိမဝန္တာတောင်စွယ်များမှ တောင်ဘက်ရှိ ပင်လယ်ရေပြာပြာအထိ သဘာဝ အလှတရားများ ပေါများသောနိုင်ငံဖြစ်ပါသည်။",
        home_sub_3 : "          လိုဏ်ဂူများ၊ သန္တာကျောက်တန်းများ၊ ရေကန်များ၊ မြစ်များ၊ ကမ်းခြေများ၊ ကျွန်းများနှင့် တောင်တန်းများစသည့် သဘာဝအလှတရားများအပြင် သမိုင်းနှင့်ယဉ်ကျေးမှုကို စိတ်ပါဝင်စားသူများအနေဖြင့် ဘုရားပုထိုးများ၊  ပွဲတော်များ၊ လူမျိုးပေါင်း ၁၃၅ မျိုးနှင့် ၎င်းတို့၏ အရသာရှိသော ဟင်းလျာမျိုးစုံတို့ကို ခံစားနိုင်မည်ဖြစ်ပါသည်။",
        home_sub_4 : "အဆင့်မြင့် သတ်မှတ်ချက်",
        home_sub_5 : "အကောင်းဆုံး တည်နေရာ",
        home_sub_6 : "အခမဲ့ ပယ်ဖျက်ခြင်း",
        home_sub_7 : "ငွေပေးချေမှု ရွေးချယ်ခြင်းများ",
        home_sub_8 : "ယခု စုံစမ်းရန်",
        slideShowOne_main_title : " အကောင်းဆုံး လည်ပတ်ရန်နေရာများ",
        slideShowOne_sub_1 : " ရွှေတိဂုံစေတီတော်သည် ကမ္ဘာပေါ်တွင် ရှေးအကျဆုံး ဗုဒ္ဓဘာသာ စေတီတော်ဖြစ်သည်ဟု သမိုင်းကြောင်းများအရသိရသည်။",
        slideShowOne_sub_2 : "မန္တလေးနန်းတော်သည် နောက်ဆုံးဘုရင်နှစ်ပါးဖြစ်သည့် မင်းတုန်းမင်းနှင့် သီပေါမင်းတို့၏ စံအိမ်တော်ဖြစ်သည်။",
        slideShowOne_sub_3 : "ပုဂံ၌ သာယာဝပြောသောစီးပွားရေးသည် ၁၁ရာစုမှ ၁၃ရာစုကြားတွင် ဘုရားကျောင်းပေါင်း ၁၀၀၀၀ ကျော်တည်ဆောက်ခဲ့သည်။",
        slideShowOne_sub_4 : "ချောင်းသာကမ်းခြေတွင် မြင်းစီးခြင်း၊ အဖွဲ့လိုက်စက်ဘီးစီးခြင်း၊ လေဖြည့်ကွင်းများ နှင့်အခြားသော ပျော်ရွင်မှုများရနိုင်သည်။",
        slideShowOne_sub_5 : "ဦးပိန်တံတားကို ၁၈၅၀ခုနှစ်ခန့်က တည်ဆောက်ခဲ့ပြီး ရှေးအကျဆုံးနှင့် အရှည်ဆုံး ကျွန်းသစ်တံတား ဖြစ်သည်။",
        slideShowOne_sub_6 : "အင်းတော်ကြီးကန်သည် မြန်မာနိုင်ငံ၏ အကြီးဆုံးသော သဘာဝအင်းကြီး ဖြစ်ပြီး ကန်၏အလယ်တွင် စေတီတော်ကို တည်ထားသည်။",
        slideShowOne_sub_7 : "အင်းဝသည် မြန်မာ၌ ၁၃၆၅ခုနှစ်မှ ၁၈၄၂ခုနှစ် အထိ နှစ်ပေါင်း ၃၆၀နီးပါး အင်းဝမြို့တော်အဖြစ် ငါးကြိမ်တိုင် ကျင်းပသတ်မှတ်ခဲ့သည်။",
        slideShowOne_sub_8 : "ပူတာအိုမြို့သည် မြန်မာနိုင်ငံ၏ မြောက်ဘက်အစွန်ဆုံး ခရိုင်မြို့ဖြစ်ပြီး ရေခဲတောင်များဝန်းရံထားသဖြင့် ရာသီဥတုအေးမြသည်။",
        slideShowOne_sub_9 : "ကျိုက်ထီးရိုးစေတီတော်သည် မြန်မာနိုင်ငံရှိ မွန်ပြည်နယ်၊ ကျိုက်ထိုမြို့အနီး ပေါင်းလောင်းတောင်ပေါ်တွင် တည်ရှိသောစေတီဖြစ်သည်။",
        slideShowOne_sub_10 : "အင်းလေးကန်သည် မြန်မာနိုင်ငံတွင် ဒုတိယ အကြီးဆုံးရေကန်ကြီးဖြစ်ပြီး ရှမ်းပြည်နယ်ရှိ ရှမ်တောင်တန်းဒေသတွင် တည်ရှိသည်။",
        slideShowOne_sub_11 : "ယခု ရှာဖွေလိုက်ပါ",
        SlideShowTwo_title_sub : "ကျွန်ူပ်တို့အကြိုက်ဆုံးအခန်းများ",
        SlideShowTwo_subTitle_1 : "Chatrium Hotel & Residences",
        SlideShowTwo_subTitle_2 : "One Bedroom Ocean Suit",
        SlideShowTwo_subTitle_3 : "The Entertainment Suite",
        SlideShowTwo_sub_1_1 : "၄၀ - နတ်မောက်လမ်း , တာမွေကြီးရပ်ကွက် , ရန်ကုန် ၁၁၂၁၁",
        SlideShowTwo_sub_1_2 : "ညအိပ်ချိန် ကောင်းကောင်းလေးလိုချင်ပါသလား ၊ အလွန်သက်သောင့်သက်သာရှိသော ကုတင်များအဖြစ် အဆင့်သတ်မှတ်ခြင်းခံထားရသော အခန်းများကို ယခုဟိုတယ်တွင်ရရှိနိုင်သည်။",
        SlideShowTwo_sub_1_3 : "အပြင်ဘက် ရေကူးကန်",
        SlideShowTwo_sub_1_4 : "ရေကန် ရှုခင်း",
        SlideShowTwo_sub_1_5 : "spa နှင့် ကျန်းမာရေးစင်တာ",
        SlideShowTwo_sub_2_1 : "ရန်ကုန် မှ ၆နာရီ မောင်းနှင်ရန်",
        SlideShowTwo_sub_2_2 : "ဟိုတယ်ရှိ အခန်းတစ်ခန်းစီတွင် စားပွဲခုံတစ်လုံး၊ flat-screen တီဗီနှင့် သီးသန့်ရေချိုးခန်းတို့ ပါရှိသည်။အခန်းတိုင်းတွင် လေအေးပေးစက်နှင့် ဗီရိုတစ်လုံးရှိသည်။",
        SlideShowTwo_sub_2_3 : "ပင်လယ်ကုန်းပတ်",
        SlideShowTwo_sub_2_4 : "ပင်လယ်ရှူခင်း",
        SlideShowTwo_sub_2_5 : "လသာဆောင်",
        SlideShowTwo_sub_3_1: "၆၆ ပြည်လမ်း , ရန်ကုန် ၁၁၁၉၁",
        SlideShowTwo_sub_3_2 : "ဖျော်ဖြေရေးအတွက် ထုတ်ထားသောအခန်းတွင် ခေတ်မီသော အသံလုံစနစ် ၈၅လက်မ LEDတီဗီ နှင့် FreshBed အိပ်စက်စနစ်ပါရှိသော မာစတာအိပ်ခန်းတစ်ခု ပါဝင်သည်။",
        SlideShowTwo_sub_3_3 : "တီဗီထားရှိသောစင်ကြီး",
        SlideShowTwo_sub_3_4 : "ရုပ်ရှင်ကြည့်ရန် မျက်နှာပြင်",
        SlideShowTwo_sub_3_5 : "VR ဂိမ်းများနှင့် PlayStation ဂိမ်းများ",
        SlideShowTwo_bottom_sub : "အရံသတ်မှတ်ရန်",
        Offer_Title_sub : "ရာသီလိုက် ပွဲတော်များ",
        Offer_sub_1 : "မဟာသင်္ကြန်",
        Offer_sub_2 : "သီတင်းကျွတ်",
        Offer_sub_3 : "တောင်ကြီး တန်ဆောင်တိုင်",
        Offer_sub_4 : "ကချင် မနှော ပွဲတော်",
        Offer_sub_5 : "အင်းလေး-ဖောင်တော်ဦး",
        Offer_sub_6 : "ပွဲတော်များအားကြည့်ရန်",
        HappyMoment_sub_1 : "ကျွန်ုပ်တို့၏အပန်းဖြေစခန်းသည် အခြားများထက် မည်သည့်အရာများက သာလွန်စေသနည်း။",
        HappyMoment_sub_2 : "ခရီးသွားများသည် ပုဂံမြို့ဟောင်းသို့ လာရောက်သောအခါ ထိုမြို့ဟောင်း၏အလှအောက်တွင် အံ့သြောမင်သက်သွားကြသည်။ရွှေတိဂုံစေတီဘုရားကို မြင်သောအခါတွင်လည်း ကြည်ညိုအရိုအသေပေးကြသည်။ ",
        HappyMoment_sub_3 : "အခမဲ့ဘွတ်ကင်ချိတ်ခြင်း",
        HappyMoment_sub_4 : "၁၈,၀၀၀ကျော် မှတ်ချက်ပေးထားခြင်း",
        HappyMoment_sub_5 : "ဖော်ရွေသောဝန်ထမ်းများ",
        HappyMoment_sub_6 : "ဘဝကြီးကတိုတောင်းတယ် ၊ ကမ္ဘာကြီးကတော့ကျယ်တယ်။ သင့်ရဲ့ အကောင်းဆုံးစွန့်စားခန်းကြီးအတွက် သင်ယခုဘဲထွက်ခါလိုက်ပါ၊ သင်သွားမဲ့ ခရီးတိုင်းအတွက် ကျွန်ုပ်တို့ သင့်အားအမြဲစောင့်ကြိုနေလျက်ပါ။",
        HappyMoment_sub_7 : "ခရီးသည်တိုင်းအတွက် ကျွန်ုပ်တို့သည် ကူညီရန်အမြဲအဆင်သင့်ရှိပြီး Travel Agency မှကျွန်ုပ်တို့သည် အရာရာအားလုံးအတွက် ပြီးပြည်စုံမှုရှိအောင် သေချာစီစဥ်ပေးပါသည်။ ကျွန်ုပ်တို့၏စကားများကို သေခြာမှုရှိစေရန် ခရီးသွားများ၏သုံးသပ်ချက်များကို ကြည်ရှုနိုင်သည်။",
        HappyMoment_sub_8 : "ခရီးသွားကားများသည် အချိန်တိကျစွာရောက်သည်။ ကားများသည် သန့်ရှန်းပြီး သက်သောင့်သက်သာရှိသည်။ ယာဥ်မောင်းများသည် အရည်အချင်းပြည့်မှီပြီး ခရီးသည်များဖြင့် ခင်မင်ဆက်ဆံရေးအလွန်ကောင်းမွန်သည်။",
        HappyMoment_sub_9 : "ကျွန်ုပ်တို့၏ ပျော်ရွှင်စရာ အခိုက်အတန့်အချို့",
        Subscribe_sub_1 : "စာရင်းသွင်းပြီး အထူးလျော့စျေးများရယူပါ။",
        Subscribe_sub_2 : "မြန်မာနိုင်ငံသို့ လာရောက်လည်ပတ်လာကြသော ခရီးသွားဧည့်သည်ပြည်သူများ ကောင်းမွန်သောနေ့ရက်များကို ပိုင်ဆိုင်ကြပါစေ၊ စွဲမက်ဖွယ်ကောင်းသောမြန်မာနိုင်ငံကိုအမှတ်ရပါ။",

    },
    englishSub : {
        nav_sub_1 : "Things To Do",
        nav_sub_2 : "Place To Go",
        nav_sub_3 : "Plan Your Trip",
        nav_sub_4 : "Setting",
        navDrop_title_sub_1 : "Destination",
        navDrop_title_sub_2 : "Hotel Type",
        navDrop_title_sub_3 : "Category",
        navDrop_title_sub_4 : "Recommend to Visit",
        navDrop_title_sub_5 : "Seasonal Festivals",
        navDrop_sub_1 : "Yangon",
        navDrop_sub_2 : "Mandalay",
        navDrop_sub_3 : "Bagan",
        navDrop_sub_4 : "Pyin Oo Lwin",
        navDrop_sub_5 : "Taung Gyi",
        navDrop_sub_6 : "Kalaw",
        navDrop_sub_7 : "Mawlamyine",
        navDrop_sub_8 : "Indaw Gyi",
        navDrop_sub_9 : "Inlay",
        navDrop_sub_10 : "Puta-O",
        navDrop_sub_11 : "Rakhine",
        navDrop_sub_12 : "All",
        navDrop_sub_13 : "Hotels",
        navDrop_sub_14 : "Bungalows",
        navDrop_sub_15 : "Villas",
        navDrop_sub_16 : "Resorts",
        navDrop_sub_17 : "Restaurants",
        navDrop_sub_18 : "Beach",
        navDrop_sub_19 : "City",
        navDrop_sub_20 : "Spa",
        navDrop_sub_21 : "Nature and Wildlife",
        navDrop_sub_22 : "Golf",
        navDrop_sub_23 : "Heritage",
        navDrop_sub_24 : "Enjoy Great Time With Us",
        navDrop_sub_25 : "Get 1000 bonus points on distination",
        navDrop_sub_26 : "Discount for the special festive",
        navDrop_sub_27 : "Discount for the first time purchase",
        navDrop_sub_28 : "Register Now",
        navDrop_sub_29 : "Shwedagon Pagoda",
        navDrop_sub_30 : "Mandalay Palace",
        navDrop_sub_31 : "Chanung Thar Beach",
        navDrop_sub_32 : "Ngay Saung Beach",
        navDrop_sub_33 : "Bagan (Nyaung Oo)",
        navDrop_sub_34 : "Innwa (Mandalay)",
        navDrop_sub_35 : "Oo Pain Bridge",
        navDrop_sub_36 : "Kyit Htee Yoe Pagoda",
        navDrop_sub_37 : "Inle Lake",
        navDrop_sub_38 : "Inn Taw Gyi Lake",
        navDrop_sub_39 : "Yangon Zoo",
        navDrop_sub_40 : "Putao Mountain Climbing",
        navDrop_sub_41 : "Great Thingyan Festival",
        navDrop_sub_42 : "Thadingyut Festival",
        navDrop_sub_43 : "Taunggyi Tazaungdaing Festival",
        navDrop_sub_44 : "Kachin Manaw Festival",
        navDrop_sub_45 : "Shan New Year Festival",
        navDrop_sub_46 : "Inle-Phaung Daw Oo Pagoda Festival",
        heroLand_sub_1 : "A World Of Luxury", 
        heroLand_sub_2 : "Awaits You",
        heroLand_sub_3 : "Discover a New Look of Luxury Resorts",
        heroLand_sub_4 : "Discover More",
        home_sub_1 : "Span Your Valuable Time In Myanmar",
        home_sub_2 : "Myanmar is an unexplored natural and cultural wonder that offers one of the best authentic experiences for the traveller to Asia. From the snow-covered rugged Himalayas in the north to the pristine deep blue waters in the south, Myanmar is a land blessed and abundant.",
        home_sub_3 : "The natural attractions include caves, corals, lakes, rivers, beaches, islands, and mountains, whilst the connoisseur of culture and history will find pagodas, an array of vibrant festivals, 135 tribes and a spread of delicious cuisine to tantalise their taste buds.",
        home_sub_4 : "Have High Rating",
        home_sub_5 : "Best Location",
        home_sub_6 : "Free Cancellation",
        home_sub_7 : "Payment Options",
        home_sub_8 : "Explore now",
        slideShowOne_main_title : "Best Place To Visit",
        slideShowOne_title_sub_1 : "Spa & Wellness",
        slideShowOne_title_sub_2 : "Wedding & Romance",
        slideShowOne_title_sub_3 : "Activites",
        slideShowOne_title_sub_4 : "Event Calendar",
        slideShowOne_title_sub_5 : "Dining",
        slideShowOne_title_sub_6 : "Fitness Center",
        slideShowOne_title_sub_7 : "Shop",
        slideShowOne_sub_1 : "Shwedagon Pagoda is the oldest Buddhist Pagoda in the world by according to history.",
        slideShowOne_sub_2 : "Mandalay Palace was the primary royal residence of King Mindon and King Thibaw, the last two kings of the country.",
        slideShowOne_sub_3 : "Bagan's prosperous economy built over 10,000 temples between the 11th and 13th centuries.",
        slideShowOne_sub_4 : "Classic beach activities are aplenty in Chaung tha,including horse riding,bicycle and quad bike hire and indlatable rings.",
        slideShowOne_sub_5 : "Oo Pain bridge was built around 1850 and is believed to be the oldest and longest teakwood bridge in the world.",
        slideShowOne_sub_6 : "Inn Taw Gyi Lake is the largest natural lake in Myanmar and Shwe ManZhu Pagoda is built on the middle of Lake",
        slideShowOne_sub_7 : "Inwa was the capital of Myanmar for nearly 360years ,on five separate occasions,from 1365 to 1842.",
        slideShowOne_sub_8 : "Putao City is the northernmost district city of Myanmar and sorrounded by glaciers,the climate is cool.",
        slideShowOne_sub_9 : "Kyaik Hyo Pagoda is located on Paung Long Mountain near the city of Kyaitho in Mon State of Myanmar.",
        slideShowOne_sub_10: "Inle Lake is the second largest lake in Myanmar and it's located in the Shan State of Shan Hills in Myanmar",
        slideShowOne_sub_11 : "Explore now",
        SlideShowTwo_title_sub : "Our Favorite Rooms",
        SlideShowTwo_subTitle_1 : "Chatrium Hotel & Residences",
        SlideShowTwo_subTitle_2 : "One Bedroom Ocean Suit",
        SlideShowTwo_subTitle_3 : "The Entertainment Suite",
        SlideShowTwo_sub_1_1 : "40 - Natmauk St , Tamwe Township , Yangon 11211",
        SlideShowTwo_sub_1_2 : "Want a great night's sleep? This hotel was highly rated for its very comfy beds.",
        SlideShowTwo_sub_1_3 : "Outdoor swimming pool",
        SlideShowTwo_sub_1_4 : "Lake View",
        SlideShowTwo_sub_1_5 : "Spa and wellness centre",
        SlideShowTwo_sub_2_1 : "6 hours drive from Yangon",
        SlideShowTwo_sub_2_2 : "At the hotel, each room comes with a desk, a flat-screen TV and a private bathroom. Each room has air conditioning. All guest rooms have a wardrobe.",
        SlideShowTwo_sub_2_3 : "Private Deck",
        SlideShowTwo_sub_2_4 : "Ocean View",
        SlideShowTwo_sub_2_5 : "Balcony",
        SlideShowTwo_sub_3_1: "66 Pyay Rd , Yangon 11191",
        SlideShowTwo_sub_3_2 : "This versatile suite is designed for entertaining. The suite features state-of-the-art audiovisuals, 85-inch LED TV and ....",
        SlideShowTwo_sub_3_3 : "Entertainment Wall",
        SlideShowTwo_sub_3_4 : "Cinema Screen",
        SlideShowTwo_sub_3_5 : "Virtual Reality & PlayStation Games",
        SlideShowTwo_bottom_sub : "Reserve",
        Offer_Title_sub : "Seasonal Festivals",
        Offer_sub_1 : "Great Thingyan",
        Offer_sub_2 : "Thadingyut",
        Offer_sub_3 : "Taunggyi Tazaungdaing",
        Offer_sub_4 : "Kachin Manaw",
        Offer_sub_5 : "Inle-Phaung Daw Oo",
        Offer_sub_6 : "View All Festivals",
        HappyMoment_sub_1 : "What makes our resort best than others?",
        HappyMoment_sub_2 : "When passenger arrived at Bagan(Ancient City) Resort, they were struck by the stunning beauty of the location and they are reverence when they see the SHWEDAGON Pagoda ",
        HappyMoment_sub_3 : "Hassle Free Booking",
        HappyMoment_sub_4 : "18,000 Reviews",
        HappyMoment_sub_5 : "Service of staffs",
        HappyMoment_sub_6 : "Life is short and the world is wide!!.To get the best your adventure you just need to leave and go where you like.We are waiting for you.",
        HappyMoment_sub_7 : "we are always ready to help our customers and we make sure that everything is arranged perfectly with Travel Agency. Don’t take our word for it but have a look at the reviews of our customers.",
        HappyMoment_sub_8 : "The bus arrived at the correct time and was clean and comfortable. Our driver Rob was very good and friendly.",
        HappyMoment_sub_9 : "Some Of Our Happy Moments",
        Subscribe_sub_1 : "Subscribe & Get Special Discount!",
        Subscribe_sub_2 : "May the touriste visiting Myanmar have good days and dream of enchanting Myanmar.",
        Footer_sub_1 : "Our business has been operating since 2016",
    },
    Destination_Of_Myanmar_Images : {
        'Yangon' : {
            image_1 : "https://www.grandmercure.com/wp-content/uploads/2020/04/YANGON_3-shutterstock_403828075__001-2200x1200.jpg",
            image_2 : "https://www.wendywutours.com.au/resource/upload/734/banner-yangon.jpg",
            image_3 : "https://i.pinimg.com/564x/7e/62/e8/7e62e84620cc2354f8010d88daea270a.jpg",
            image_4 : "https://i.pinimg.com/564x/95/d3/d1/95d3d1e759bf0fbd16136cc71d495905.jpg",
            image_5 : "https://i.pinimg.com/564x/58/80/4b/58804b12ee8c6bf9299e108118997ce1.jpg",
            image_6 : "https://i.pinimg.com/564x/e2/b8/5e/e2b85e38e15f17051c8ead224007b8f3.jpg",
        },
        'Mandalay' : {
            image_1 : "https://i.pinimg.com/originals/d4/66/27/d46627cb8f1b76eaf3e01f4f882eda39.jpg",
            image_2 : "https://i.pinimg.com/564x/2c/f2/3a/2cf23ace34500fca0e2c5eaa55c28902.jpg",
            image_3 : "https://m.media-amazon.com/images/I/71HQO0GKQTL._AC_SX679_.jpg",
            image_4 : "https://i.pinimg.com/564x/54/83/0f/54830ffdf990f7b36719e1e9b701a527.jpg",
            image_5 : "https://i.pinimg.com/564x/ec/e7/d9/ece7d9fac03c4b15535bdb487ee76deb.jpg",
            image_6 : "https://i.pinimg.com/564x/7d/37/bd/7d37bd2ac637db2cb9f3f841f284eff4.jpg",
        },
        'Bagan' : {
            image_1 : "https://envoyexcellency.com/wp-content/uploads/2023/12/Temples-of-Bagan-Restoration.jpg",
            image_2 : "https://i.pinimg.com/564x/02/cf/c5/02cfc58317efad1ae780857a036c5588.jpg",
            image_3 : "https://www.asiapearltravels.com/images/hotels/kumudara_hotel_on_bagan_map.jpg",
            image_4 : "https://i.pinimg.com/564x/85/61/ab/8561ab37ebae710223b40ad29db658bd.jpg",
            image_5 : "https://i.pinimg.com/564x/ca/f6/8d/caf68de6af037ec5c8d9ef9bcb8424f7.jpg",
            image_6 : "https://i.pinimg.com/564x/5d/d1/b5/5dd1b515bb59c0031820c56cf0432742.jpg",
        },
        'Pyin Oo Lwin' : {
            image_1 : "https://i.pinimg.com/originals/cc/0f/f2/cc0ff21533d1a991805f90a42a2c1929.jpg",
            image_2 : "https://d13jio720g7qcs.cloudfront.net/images/tours/800_450/5644052fa6feb.jpg",
            image_3 : "https://4.bp.blogspot.com/-ZPb-hjxHYyM/UuSAqbCrZNI/AAAAAAAAZPM/SCkQgDFRUC0/s1600/pyinoolwin_map.gif",
            image_4 : "https://i.pinimg.com/564x/bc/58/3f/bc583f42d0bdb9f8d43d9e3ed0ca56e7.jpg",
            image_5 : "https://i.pinimg.com/564x/e3/d2/18/e3d218c40acff95df9bf0236c21978da.jpg",
            image_6 : "https://i.pinimg.com/564x/bf/b2/f7/bfb2f7bca1a85e1f9dda08a642f7db78.jpg",
        },
        'Taung Gyi' : {
            image_1 : "https://upload.wikimedia.org/wikipedia/commons/b/b9/Shwe_Bone_Pwint_Pagoda%2C_Taunggyi%2CShan.jpg",
            image_2 : "https://miro.medium.com/v2/resize:fit:650/1*F1vWlgd8GdG3qnQVSlDleg.jpeg",
            image_3 : "https://maps-myanmar.com/img/1200/taunggyi-myanmar-map.jpg",
            image_4 : "https://i.pinimg.com/564x/74/29/a3/7429a311541e3869484b7755c775537e.jpg",
            image_5 : "https://i.pinimg.com/564x/18/b7/4f/18b74ff49a1de384610069f8a13ab570.jpg",
            image_6 : "https://i.pinimg.com/564x/c0/02/7b/c0027bfd74c322a147d1cfc27ae8dcec.jpg",
        },
        'Kalaw' : {
            image_1 : "https://planetofhotels.com/guide/sites/default/files/styles/paragraph__live_banner__lb_image__1880bp/public/live_banner/Kalaw_0.jpg",
            image_2 : "https://i.pinimg.com/564x/bc/e7/98/bce79827af0bde8e78cad7811ca1e280.jpg",
            image_3 : "https://cdn.sanity.io/images/ul272611/production/acd840628acd1f8d82be459b363d1e6cd5e4d42c-1046x1065.jpg?rect=0,9,1046,1046&w=1200&h=1200&fit=max&auto=format",
            image_4 : "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/ad/65/54/peut-etre-pas-tres-birman.jpg?w=600&h=400&s=1",
            image_5 : "https://i.pinimg.com/564x/8e/ff/5b/8eff5bad20b2670e1723547d0b1461b8.jpg",
            image_6 : "https://i.pinimg.com/564x/cb/df/c9/cbdfc94125916203e026e9763f603941.jpg",
        },
        'Mawlamyine' : {
            image_1 : "https://burmatravel.com/myanmar-photos/2016/04/golden-rock-Kyaikhtiyo-myanmar-2-1.jpg",
            image_2 : "https://as1.ftcdn.net/v2/jpg/04/62/72/64/1000_F_462726409_6n4T0EGgWKoouIWLa7BGM5rZYS9YTApM.jpg",
            image_3 : "https://m.media-amazon.com/images/I/71fsFTbVo2L._AC_SX679_.jpg",
            image_4 : "https://d13jio720g7qcs.cloudfront.net/images/destinations/origin/5d15c37ce5aec.jpg",
            image_5 : "https://i.pinimg.com/564x/1e/c6/1f/1ec61f7d81947b6f0b54820f728a9b51.jpg",
            image_6 : "https://i.pinimg.com/564x/e3/d2/53/e3d253706f1b0e75e72cc38eea13b8f4.jpg",
        },
        'Indaw Gyi' : {
            image_1 : "https://kdng.org/wp-content/uploads/2018/12/Indawgyi-Lake-gets-UNESCO-designation.jpg",
            image_2 : "https://ttgasia.2017.ttgasia.com/wp-content/uploads/sites/2/2017/08/Indawgyi-Lake.jpg",
            image_3 : "https://indawgyilake.com/sites/indawgyilake.com/files/northern-img/maplake90_1.png?t=1706415599439",
            image_4 : "https://i.pinimg.com/564x/05/bd/c4/05bdc4bd85dba0550c6eabcd9ca7a0e8.jpg",
            image_5 : "https://i.pinimg.com/564x/f2/b0/c1/f2b0c1ddae49d2e8d54f36ae046350f1.jpg",
            image_6 : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Indawgyi_Lake.JPG/800px-Indawgyi_Lake.JPG",
        },
        'Inlay' : {
            image_1 : "https://www.vietnamparadisetravel.com/wp-content/uploads/i/40/Inle-Lake.jpg",
            image_2 : "https://i.pinimg.com/564x/b6/2c/20/b62c206d93cb82e70781f3c744762787.jpg",
            image_3 : "https://images.squarespace-cdn.com/content/v1/545012a9e4b0988576f6b699/3dce29b9-783d-4769-b4cf-85247fa3f23b/inle-lake-tourist-guide-map.png",
            image_4 : "https://i.pinimg.com/564x/7c/77/51/7c77513e302b3fe8272411913b355cf9.jpg",
            image_5 : "https://i.pinimg.com/564x/01/83/4e/01834e19bc7dd8aa675ce4b93993f849.jpg",
            image_6 : "https://myanmartrains.info/wp-content/uploads/2019/02/Hpaung-Daw-U-Pagoda-near-Inle-Lake.jpg",
        },
        'Puta-O' : {
            image_1 : "https://www.travelloops.com/userfiles/putao.jpg",
            image_2 : "https://images.hive.blog/0x0/https://steemitimages.com/DQmVXQEcXjCNFjnfhRY9B51csiebsRr5F7QkNWW2BdDhvow/FB_IMG_1505095562812.jpg",
            image_3 : "https://rainforestjournalismfund.org/sites/default/files/styles/height_500/public/protected_areas_map_0.png.webp?itok=bQFLY0Np",
            image_4 : "https://cdn.myanmarseo.com/file/client-cdn/2023/12/997ACC7B-656E-4417-A00D-CE7C7FE87B15.jpeg",
            image_5 : "https://i.pinimg.com/564x/9d/b9/2c/9db92ce77068257a9b5b37d202f745d6.jpg",
            image_6 : "https://media.istockphoto.com/id/1341407209/photo/rural-karst-landscape.jpg?s=612x612&w=0&k=20&c=NS2qtCzgcGbh4gHI3FIITC5fBlERKuTcP_pHGjgefic=",
        },
        'Rakhine' : {
            image_1 : "https://beta.myanmarvoyages.com/wp-content/uploads/2020/09/Oriental-Ballooning-Ngapali-13.jpg",
            image_2 : "https://miro.medium.com/v2/resize:fit:650/1*08lwNiDTLZW3HhsH4b5Jkw.jpeg",
            image_3 : "https://upload.wikimedia.org/wikipedia/commons/8/80/Map_of_Rakhine_%28Arakan%29_State_in_Myanmar.png",
            image_4 : "https://media-cdn.tripadvisor.com/media/photo-c/1280x250/0d/c3/19/73/ko-thaung-temple-3.jpg",
            image_5 : "https://i.pinimg.com/564x/51/97/7e/51977ea565f94184b2851600e26ac50e.jpg",
            image_6 : "https://i.pinimg.com/564x/7d/df/1e/7ddf1ec59ab38b003a5e6ed017808c1b.jpg",
        },
    },
    Destination_Of_Myanmar_EnglishSub:{
        'Yangon' : {
            text_1:"Yangon",
            text_2:"About Of",
            text_3:"Facts Of",
            text_4:"Fascination",
            text_5:"History Of",
            text_6:"Top Attractions",
            text_7:"Of Yangon",
            para_text_1:"Formerly known as Rangoon, Yangon is a historical city and one of the most well-known cities in the country. Yangon was Myanmar’s administrative capital before Nay Pyi Taw was named as the capital city. Yangon is the country’s most prominent commercial centre as well as the largest city of the country with a population of more than 7 million people. The name ‘Yangon’ is a combination of the Burmese words ‘Yan’ meaning ‘enemies’ and ‘Koun’ meaning ‘run out of’. The combination of words commonly translates as ‘End of Strife’. During the colonial era, Yangon was called ‘Rangoon’. Till the mid-1990s, Yangon mostly had a traditional setting. As people started moving in, a necessity to expand the area of the city was felt. The city grew rapidly towards the north where the Yangon International Airport is located now.",
            para_text_2:"The local people in the city are very friendly and hospitable. They will understand you even if you don’t have a common language to communicate.The streets of Yangon are dotted with street food vendors selling fresh and yummy local cuisine. Don’t miss trying everything!",
            para_text_3:"Yangon has a rich history behind it which dates back to the 11th century when the Mons who lived in Lower Burma the city and named it Dagon. It was a small fishing village centred around the Shwedagon Pagoda. When King Alaungpaya took over Dagon in 1755, he changed the name to Yangon. The British conquered Yangon after the First Anglo-Burmese War (1824-1826) but returned Yangon back to Burmese administration as the war ended. They seized Yangon and lower Burma moved to after the Second Anglo-Burmese War in 1852. Yangon was the epicentre of Myanmar’s struggle for independence. When Myanmar gained independence in 1948, Yangon was made the capital of the country.",
            
        },
        'Mandalay' : {
            text_1:"Mandalay",
            text_2:"About Of",
            text_3:"Facts Of",
            text_4:"Fascination",
            text_5:"History Of",
            text_6:"Top Attractions",
            text_7:"Of Mandalay",
            para_text_1:"Formerly known as Rangoon, Yangon is a historical city and one of the most well-known cities in the country. Yangon was Myanmar’s administrative capital before Nay Pyi Taw was named as the capital city. Yangon is the country’s most prominent commercial centre as well as the largest city of the country with a population of more than 7 million people. The name ‘Yangon’ is a combination of the Burmese words ‘Yan’ meaning ‘enemies’ and ‘Koun’ meaning ‘run out of’. The combination of words commonly translates as ‘End of Strife’. During the colonial era, Yangon was called ‘Rangoon’. Till the mid-1990s, Yangon mostly had a traditional setting. As people started moving in, a necessity to expand the area of the city was felt. The city grew rapidly towards the north where the Yangon International Airport is located now.",
            para_text_2:"The local people in the city are very friendly and hospitable. They will understand you even if you don’t have a common language to communicate.The streets of Yangon are dotted with street food vendors selling fresh and yummy local cuisine. Don’t miss trying everything!",
            para_text_3:"Yangon has a rich history behind it which dates back to the 11th century when the Mons who lived in Lower Burma the city and named it Dagon. It was a small fishing village centred around the Shwedagon Pagoda. When King Alaungpaya took over Dagon in 1755, he changed the name to Yangon. The British conquered Yangon after the First Anglo-Burmese War (1824-1826) but returned Yangon back to Burmese administration as the war ended. They seized Yangon and lower Burma moved to after the Second Anglo-Burmese War in 1852. Yangon was the epicentre of Myanmar’s struggle for independence. When Myanmar gained independence in 1948, Yangon was made the capital of the country.",
            
        },
        'Bagan' : {},
        'Pyin Oo Lwin' : {},
        'Taung Gyi' : {},
        'Kalaw' : {},
        'MawlamyIne' : {},
        'Indaw Gyi' : {},
        'Inlay' : {},
        'Puta-O' : {},
        'Rakhine' : {},
    },
    Destination_Of_Myanmar_MyanmarSub:{
        'Yangon' : {
            text_1:"ရန်ကုန်",
            text_2:"About Of",
            text_3:"Facts Of",
            text_4:"Fascination",
            text_5:"History Of",
            text_6:"Top Attractions",
            text_7:"Of Yangon",
            para_text_1:"Formerly known as Rangoon, Yangon is a historical city and one of the most well-known cities in the country. Yangon was Myanmar’s administrative capital before Nay Pyi Taw was named as the capital city. Yangon is the country’s most prominent commercial centre as well as the largest city of the country with a population of more than 7 million people. The name ‘Yangon’ is a combination of the Burmese words ‘Yan’ meaning ‘enemies’ and ‘Koun’ meaning ‘run out of’. The combination of words commonly translates as ‘End of Strife’. During the colonial era, Yangon was called ‘Rangoon’. Till the mid-1990s, Yangon mostly had a traditional setting. As people started moving in, a necessity to expand the area of the city was felt. The city grew rapidly towards the north where the Yangon International Airport is located now.",
            para_text_2:"The local people in the city are very friendly and hospitable. They will understand you even if you don’t have a common language to communicate.The streets of Yangon are dotted with street food vendors selling fresh and yummy local cuisine. Don’t miss trying everything!",
            para_text_3:"Yangon has a rich history behind it which dates back to the 11th century when the Mons who lived in Lower Burma the city and named it Dagon. It was a small fishing village centred around the Shwedagon Pagoda. When King Alaungpaya took over Dagon in 1755, he changed the name to Yangon. The British conquered Yangon after the First Anglo-Burmese War (1824-1826) but returned Yangon back to Burmese administration as the war ended. They seized Yangon and lower Burma moved to after the Second Anglo-Burmese War in 1852. Yangon was the epicentre of Myanmar’s struggle for independence. When Myanmar gained independence in 1948, Yangon was made the capital of the country.",
            
        },
        'mandalay' : {},
        'Bagan' : {},
        'Pyin Oo Lwin' : {},
        'Taung Gyi' : {},
        'Kalaw' : {},
        'MawlamyIne' : {},
        'Indaw Gyi' : {},
        'Inlay' : {},
        'Puta-O' : {},
        'Rakhine' : {},
    },
    Destination_Of_Myanmar : {},
    mother_sub : {},
    page_sub : "English",
}

export const DataCenter = createSlice({
    name:'dataCenter',
    initialState,
    reducers : {
        start_language : (state,action) => {
            if(action.payload === 'English'){
                state.mother_sub = state.englishSub
                state.Destination_Of_Myanmar = state.Destination_Of_Myanmar_EnglishSub
            }else if(action.payload === 'Myanmar'){
                state.mother_sub = state.myanmarSub
                state.Destination_Of_Myanmar = state.Destination_Of_Myanmar_MyanmarSub
            }else{
                state.mother_sub = state.englishSub
                state.Destination_Of_Myanmar = state.Destination_Of_Myanmar_EnglishSub
            }
        },
        change_Myanmar_sub : (state) => {
            state.mother_sub = state.myanmarSub
            state.Destination_Of_Myanmar = state.Destination_Of_Myanmar_MyanmarSub
            state.page_sub = "Myanmar"
        },
        change_English_sub : (state) => {
            state.mother_sub = state.englishSub
            state.Destination_Of_Myanmar = state.Destination_Of_Myanmar_EnglishSub
            state.page_sub = "English"
        },
       
    }
})
export const {change_Myanmar_sub,change_English_sub,start_language} = DataCenter.actions
export default DataCenter.reducer